First stable build
bottleneckco/watched pull request #7
Opened 2019-06-08 07:18 UTC by elcoms

2019-06-09 08:22 UTC, duncanleo requested changes
Some changes to be made. Add the babel plugin to `package.json` so that the Netlify PR build will succeed

2019-06-09 08:22 UTC, duncanleo commented on .babelrc
> +  "plugins": [ "@babel/plugin-proposal-class-properties"]
please add this plugin to `package.json`

2019-06-09 08:22 UTC, duncanleo commented on components/AddShow/index.js
> +            document.getElementById('addShowForm').reset();
I don't think you are supposed to have element queries in React components

cc @chesterhow

2019-06-09 08:22 UTC, duncanleo commented on components/ButtonTags/index.js
> +    document.getElementById(tags.name).style.filter = this.state.buttons[tags.name] ? 'brightness(80%)' : 'brightness(110%)';
same as above

2019-06-09 08:22 UTC, duncanleo commented on components/ContentPage/index.js
> +      list = (this.state.user.watchlist.allShows) ? this.state.user.watchlist.allShows : [];
this can be simplified to 

```js
      list = this.state.user.watchlist.allShows || [];
```

2019-06-09 10:45 UTC, elcoms commented on components/AddShow/index.js
> +            document.getElementById('addShowForm').reset();
I need it lol

2019-06-09 10:47 UTC, elcoms commented on components/ContentPage/index.js
> +      list = (this.state.user.watchlist.allShows) ? this.state.user.watchlist.allShows : [];
oh damn. thanks

2019-06-10 01:46 UTC, chesterhow commented on components/AddShow/index.js
> +            document.getElementById('addShowForm').reset();
I think its okay but it would be cleaner to abstract it into a function. Also you can probably use refs instead of element queries See: https://reactjs.org/docs/refs-and-the-dom.html

2019-06-10 01:49 UTC, chesterhow commented on components/ButtonTags/index.js
> +    document.getElementById(tags.name).style.filter = this.state.buttons[tags.name] ? 'brightness(80%)' : 'brightness(110%)';
You don't need to use arrow functions here. Just write functions the same way as your render function.
```js
handleClick(tags, index) {
  ...
}
```

2019-06-10 01:50 UTC, chesterhow commented on components/ContentHeader/index.js
> +    }
I believe these belong in styles.scss

2019-06-10 01:54 UTC, chesterhow commented on LICENSE
> -SOFTWARE.
Maybe don't delete your license

2019-06-10 02:05 UTC, elcoms commented on components/AddShow/index.js
> +            document.getElementById('addShowForm').reset();
ok i try

2019-06-10 02:12 UTC, elcoms commented on components/ContentHeader/index.js
> +    }
ohshit right, i didnt think i could put it there

2019-06-10 14:43 UTC, elcoms commented on components/AddShow/index.js
> +            document.getElementById('addShowForm').reset();
Yep, if I were to use ref, I'll need to create a ref for each button, soooo I don't think so.

2019-06-11 02:18 UTC, chesterhow commented on components/AddShow/index.js
> +            document.getElementById('addShowForm').reset();
Aren't you making a ref to the form element only?

2019-06-11 04:07 UTC, elcoms commented on components/AddShow/index.js
> +            document.getElementById('addShowForm').reset();
oh I did do that. Huh, I thought I was commenting under buttontags component oops

2019-06-25 01:18 UTC, merged